version: '3.4'

services:
  theandromedaproject:
    image: theandromedaproject
    build:
      context: .
      dockerfile: ./Dockerfile

  nextcloud:
    build:
      context: ./Nextcloud
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html

  container1:
    image: container1_image
    build:
      context: ./Container1
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - container1_data:/path/to/data

  container2:
    image: container2_image
    build:
      context: ./Container2
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - container2_data:/path/to/data

volumes:
  nextcloud_data:
  container1_data:
  container2_data:
